### ISSUE TITLE
trouble installing to bin="~/bin" under linux

### ISSUE THREAD

**Issue by mgr327** [LilithHafner/UpdateJulia.jl#23]
Tried

`update_julia("1.9", dry_run=false, systemwide=false, bin="~/bin")`

which I hoped would install in the `bin` directory in the home directory. Instead got the directory '\~' created, and the link installed in '\~'/bin 

Thank you

**Comment by LilithHafner** [comment]
Julia does not automatically tilde-expand (see, e.g. https://github.com/JuliaLang/julia/issues/1136). I've added manual expansion and this should be fixed in the current release (0.4.2).
